<?php

require_once APPPATH.'views/vendor/autoload.php';

/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Klien extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_klien');
        $this->load->library('Loader');
        $uri = $this->uri->segment(1);
        $uri2 = $this->uri->segment(2);
        //var_dump($uri);
        if (!$this->session->has_userdata('status')) {
           
                if ( $uri != 'daftar' & $uri != 'forgot' & $uri2 != 'lupa_sandi') {
                    $data['_view'] = 'v_home/index';
                    $data['_landing'] = true;
                    $this->load->view('layouts/content',$data);
                }
            
        }else{
          
        }

        error_reporting(0);
    } 

    /*
     * Listing of klien
     */
    function index()
    {
        if (($this->session->userdata['status']=='login') &  ($this->session->userdata['sts']==1)) {
            $params['limit'] = RECORDS_PER_PAGE;    
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
            $config = $this->config->item('pagination');
            $config['base_url'] = site_url('klien/index?');
            $config['total_rows'] = $this->M_klien->get_all_klien_count();
            $this->pagination->initialize($config);
            $data['klien'] = $this->M_klien->get_all_klien($params);        
            $data['_view'] = 'v_klien/index';
            $data['_landing'] = false;
            $data['judul'] = "Data klien";
            $load = $this->loader->load($data);
            $this->load->view('layouts/content',$load);
        } else {
            redirect('login','refresh');
        }
    }

    function rules(){
        $this->form_validation->set_message('max_length', '{field} tidak dapat lebih dari {param} karakter.');
        $this->form_validation->set_message('min_length', '{field} tidak dapat kurang dari {param} karakter.');
        $this->form_validation->set_message('required', 'Memerlukan {field}.');
        $this->form_validation->set_message('valid_email', '{field} tidak valid.');
        $this->form_validation->set_message('matches', '{field} tidak serupa.');
        $this->form_validation->set_message('is_unique', '{field} telah digunakan.');
    }
    /*
     * Adding a new klien
     */
    function add()
    {    
        if ($this->session->has_userdata('status')&& ($this->session->userdata('level')=='Admin' || $this->session->userdata('level')=='Kepala Kantor')) {
        $this->load->library('form_validation');
        $this->form_validation->set_rules('kln_no','Nomor Klien','callback_cek_no');
        $this->form_validation->set_rules('kln_nm','Nama Lengkap','required|max_length[45]');
        $this->form_validation->set_rules('kln_tlp','Nomor Telepon','required|trim|min_length[10]|max_length[18]');
        $this->form_validation->set_rules('kln_alm','Alamat','required|max_length[255]');
        $this->form_validation->set_rules('kln_snd','Kata sandi','required|max_length[30]');
        $this->form_validation->set_rules('kln_eml','Email','required|max_length[30]|is_unique[tb_direktur.kln_eml]');
        $this->rules();
        if($this->form_validation->run())     
        {   
            $tgl = strtotime($this->input->post('kln_tll'));
            $tgl = date('Y-m-d',$tgl);
            $params = array(
                'kln_no' => $this->kodeotomatis(),
                'kln_nm' => $this->input->post('kln_nm'),
                'kln_tlp' => trim($this->input->post('kln_tlp')),
                'kln_alm' => $this->input->post('kln_alm'),
                'kln_eml' => $this->input->post('kln_eml'),
                'kln_snd' => $this->input->post('kln_snd'),
                'kln_sts' => 1
            );
            
            $klien_id = $this->M_klien->add_klien($params);
            if ($klien_id) {
                $pesan='
                    <!DOCTYPE html>
                    <html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
                    <head>
                        <meta charset="utf-8"> <!-- utf-8 works for most cases -->
                        <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldnt be necessary -->
                        <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
                        <meta name="x-apple-disable-message-reformatting">  <!-- Disable auto-scale in iOS 10 Mail entirely -->
                        <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

                        <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">

                        <!-- CSS Reset : BEGIN -->
                        <style>

                            /* What it does: Remove spaces around the email design added by some email clients. */
                            /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
                            html,
                    body {
                        margin: 0 auto !important;
                        padding: 0 !important;
                        height: 100% !important;
                        width: 100% !important;
                        background: #f1f1f1;
                    }

                    /* What it does: Stops email clients resizing small text. */
                    * {
                        -ms-text-size-adjust: 100%;
                        -webkit-text-size-adjust: 100%;
                    }

                    /* What it does: Centers email on Android 4.4 */
                    div[style*="margin: 16px 0"] {
                        margin: 0 !important;
                    }

                    /* What it does: Stops Outlook from adding extra spacing to tables. */
                    table,
                    td {
                        mso-table-lspace: 0pt !important;
                        mso-table-rspace: 0pt !important;
                    }

                    /* What it does: Fixes webkit padding issue. */
                    table {
                        border-spacing: 0 !important;
                        border-collapse: collapse !important;
                        table-layout: fixed !important;
                        margin: 0 auto !important;
                    }

                    /* What it does: Uses a better rendering method when resizing images in IE. */
                    img {
                        -ms-interpolation-mode:bicubic;
                    }

                    /* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */
                    a {
                        text-decoration: none;
                    }

                    /* What it does: A work-around for email clients meddling in triggered links. */
                    *[x-apple-data-detectors],  /* iOS */
                    .unstyle-auto-detected-links *,
                    .aBn {
                        border-bottom: 0 !important;
                        cursor: default !important;
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }

                    /* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */
                    .a6S {
                        display: none !important;
                        opacity: 0.01 !important;
                    }

                    /* What it does: Prevents Gmail from changing the text color in conversation threads. */
                    .im {
                        color: inherit !important;
                    }

                    /* If the above doesnt work, add a .g-img class to any image in question. */
                    img.g-img + div {
                        display: none !important;
                    }

                    /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */
                    /* Create one of these media queries for each additional viewport size youd like to fix */

                    /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */
                    @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
                        u ~ div .email-container {
                            min-width: 320px !important;
                        }
                    }
                    /* iPhone 6, 6S, 7, 8, and X */
                    @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
                        u ~ div .email-container {
                            min-width: 375px !important;
                        }
                    }
                    /* iPhone 6+, 7+, and 8+ */
                    @media only screen and (min-device-width: 414px) {
                        u ~ div .email-container {
                            min-width: 414px !important;
                        }
                    }


                        </style>

                        <!-- CSS Reset : END -->

                        <!-- Progressive Enhancements : BEGIN -->
                        <style>

                            .primary{
                        background: #6a5acd;
                    }
                    .bg_white{
                        background: #ffffff;
                    }
                    .bg_light{
                        background: #f7fafa;
                    }
                    .bg_black{
                        background: #000000;
                    }
                    .bg_dark{
                        background: rgba(0,0,0,.8);
                    }
                    .email-section{
                        padding:2.5em;
                    }

                    /*BUTTON*/
                    .btn{
                        padding: 10px 15px;
                        display: inline-block;
                    }
                    .btn.btn-primary{
                        border-radius: 5px;
                        background: #6a5acd;
                        color: #ffffff;
                    }
                    .btn.btn-white{
                        border-radius: 5px;
                        background: #ffffff;
                        color: #000000;
                    }
                    .btn.btn-white-outline{
                        border-radius: 5px;
                        background: transparent;
                        border: 1px solid #fff;
                        color: #fff;
                    }
                    .btn.btn-black-outline{
                        border-radius: 0px;
                        background: transparent;
                        border: 2px solid #000;
                        color: #000;
                        font-weight: 700;
                    }
                    .btn-custom{
                        color: rgba(0,0,0,.3);
                        text-decoration: underline;
                    }

                    h1,h2,h3,h4,h5,h6{
                        font-family: "Poppins", sans-serif;
                        color: #000000;
                        margin-top: 0;
                        font-weight: 400;
                    }

                    body{
                        font-family: "Poppins", sans-serif;
                        font-weight: 400;
                        font-size: 15px;
                        line-height: 1.8;
                        color: rgba(0,0,0,.4);
                    }

                    a{
                        color: #33cf;
                    }

                    table{
                    }
                    /*LOGO*/

                    .logo h1{
                        margin: 0;
                    }
                    .logo h1 a{
                        color: #339;
                        font-size: 24px;
                        font-weight: 700;
                        font-family: "Poppins", sans-serif;
                    }

                    /*HERO*/
                    .hero{
                        position: relative;
                        z-index: 0;
                    }

                    .hero .text{
                        color: rgba(0,0,0,.3);
                    }
                    .hero .text h2{
                        color: #000;
                        font-size: 34px;
                        margin-bottom: 0;
                        font-weight: 200;
                        line-height: 1.4;
                    }
                    .hero .text h3{
                        font-size: 24px;
                        font-weight: 300;
                    }
                    .hero .text h2 span{
                        font-weight: 600;
                        color: #000;
                    }

                    .text-author{
                        bordeR: 1px solid rgba(0,0,0,.05);
                        max-width: 50%;
                        margin: 0 auto;
                        padding: 2em;
                    }
                    .text-author img{
                        border-radius: 50%;
                        padding-bottom: 20px;
                    }
                    .text-author h3{
                        margin-bottom: 0;
                    }
                    ul.social{
                        padding: 0;
                    }
                    ul.social li{
                        display: inline-block;
                        margin-right: 10px;
                    }

                    /*FOOTER*/

                    .footer{
                        border-top: 1px solid rgba(0,0,0,.05);
                        color: rgba(0,0,0,.5);
                    }
                    .footer .heading{
                        color: #000;
                        font-size: 20px;
                    }
                    .footer ul{
                        margin: 0;
                        padding: 0;
                    }
                    .footer ul li{
                        list-style: none;
                        margin-bottom: 10px;
                    }
                    .footer ul li a{
                        color: rgba(0,0,0,1);
                    }


                    @media screen and (max-width: 500px) {


                    }


                        </style>


                    </head>

                    <body width="100%" style="margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;">
                        <center style="width: 100%; background-color: #f1f1f1;">
                        <div style="display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;">
                          &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
                        </div>
                        <div style="max-width: 600px; margin: 0 auto;" class="email-container">
                            <!-- BEGIN BODY -->
                          <table align="center" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="margin: auto;">
                            <tr>
                              <td valign="top" class="bg_white" style="padding: 1em 2.5em 0 2.5em;">
                                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                        <td class="logo" style="text-align: center;">
                                            <h1><a href="http://kpknl-bekasi.rf.gd">KPKNL Bekasi</a></h1>
                                          </td>
                                    </tr>
                                </table>
                              </td>
                              </tr><!-- end tr -->
                                    <tr>
                              <td valign="middle" class="hero bg_white" style="padding: 2em 0 4em 0;">
                                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                        <td style="padding: 0 2.5em; text-align: center; padding-bottom: 3em;">
                                            <div class="text">
                                                <h2>Selamat, Akun anda telah disetujui !</h2>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                          <td style="text-align: center;">
                                            <div class="text-author">
                                                <img src="http://kpknl-bekasi.rf.gd/assets/img/logo.png" alt="" style="width: 100px; max-width: 600px; height: auto; margin: auto; display: block;">
                                                <h3 class="name">'.$this->input->post('kln_nm').'</h3>
                                                <span class="position">'.$this->input->post('kln_eml').'</span>
                                                <p><a href="http://kpknl-bekasi.rf.gd/" class="btn btn-primary">Buat Permohonan</a></p>
                                            </div>
                                          </td>
                                        </tr>
                                </table>
                              </td>
                              </tr><!-- end tr -->
                          <!-- 1 Column Text + Button : END -->
                          </table>


                        </div>
                      </center>
                    </body>
                    </html>
                ';
                $kirim = array(
                    'pengirim'=>'KPKNL BEKASI',
                    'penerima'=>$klien['kln_eml'],
                    'pesan'=>$pesan,
                    'judul'=>'Status Akun Klien KPKNL Bekasi',
                );
                $this->kirim_email($kirim);
                redirect('klien/index');
            }
            
        }
        else
        {            
            $data['_view'] = 'v_klien/add';
            $data['_landing'] = false;
            $data['kode'] = $this->kodeotomatis();
            $data['judul'] = "Data klien";
            $load = $this->loader->load($data);
            $this->load->view('layouts/content',$load);
        }
        }else{
            show_404();
        }
    }  

    function cetak(){
        if ($this->session->has_userdata('status')) {
            $data['logo'] = site_url('resources/img/logo.png');
            $data['judul'] = "DATA KLIEN KPKNL BEKASI";
            $data['klien'] = $this->M_klien->get_all_klien_result();
            $this->loader->cetak('L',$data);
        }else{
            redirect('login');
        }
    }

    public function cek_no($no){
        $cek = intval(substr($no, 4,3));

        if($cek==999)
        {
           $this->form_validation->set_message('cek_no', 'Data telah mencapat batas pada bulan ini');
           return FALSE;
        } 
        return TRUE;
    }

    public function get_klien(){
        header('Content-Type: application/json');
        $cek_kln = $this->input->get('kln_no');
        $cek = $this->M_klien->get_klien_by_no($cek_kln);
        echo json_encode($cek);
    }


    function get_autocomplete(){
        if (isset($_GET['term'])) {
            $result = $this->M_klien->search_klien($_GET['term']);
            if (count($result) > 0) {
                foreach ($result as $row)
                $arr_result[] = array(
                        'label'         => $row->kln_no,
                        'description'   => $row->kln_nm,
                );
                echo json_encode($arr_result);
            }
        }
    }

    /*
     * Editing a klien
     */
    function edit($kln_id)
    {   
        if ($this->session->has_userdata('status') & ($this->session->userdata('level')!='Pejabat Lelang')) {
            // check if Data klien exists before trying to edit it
            $data['klien'] = $this->M_klien->get_klien($kln_id);
            if (isset($data['klien']['kln_id'])) {
                if( $data['klien']['kln_jab']!=$this->session->userdata('level')){
                    $this->load->library('form_validation');
                    $eml =  ($this->input->post('kln_eml') !=  $data['klien']['kln_eml']) ? '|is_unique[tb_direktur.kln_eml]' : '';
                    $jab =  ($this->input->post('kln_jab') !=  $data['klien']['kln_jab']) ? '|callback_cek_jab' : '';
                    $this->form_validation->set_rules('kln_nm','Nama Lengkap','required|max_length[45]');
                    $this->form_validation->set_rules('kln_tlp','Nomor Telepon','required|trim|min_length[10]|max_length[18]');
                    $this->form_validation->set_rules('kln_alm','Alamat','required|max_length[255]');
                    $this->form_validation->set_rules('kln_snd','Kata sandi','required|max_length[30]');
                    $this->form_validation->set_rules('kln_eml','Email klien','required|valid_email|max_length[30]'.$eml);
                    $this->rules();
                    if($this->form_validation->run())     
                    {   
                        $tgl = strtotime($this->input->post('kln_tll'));
                        $tgl = date('Y-m-d',$tgl);
                        $params = array(
                            'kln_nm' => $this->input->post('kln_nm'),
                            'kln_tlp' => trim($this->input->post('kln_tlp')),
                            'kln_alm' => $this->input->post('kln_alm'),
                            'kln_eml' => $this->input->post('kln_eml'),
                            'kln_snd' => $this->input->post('kln_snd'),
                    );
                        $this->M_klien->update_klien($kln_id,$params);    
                        redirect('klien/index');
                }else{
                        $data['_view'] = 'v_klien/edit';
                        $data['_landing'] = false;
                        $data['judul'] = "Data klien";
                        $load = $this->loader->load($data);
                        $this->load->view('layouts/content',$load);
                    }
            }
            else
                show_error('Tidak memiliki akses ini.');
            }else{
                show_error('Data klien yang diubah tidak ditemukan.');
            }
        }else{
            show_404();
        }
    }


 function profile($kln_id)
    {   
        if ($this->session->has_userdata('status')) {
            // check if Data klien exists before trying to edit it
            $data['klien'] = $this->M_klien->get_klien($this->session->userdata('id_login'));
            
            if(isset($data['klien']['kln_id']) & $data['klien']['kln_sts']==1 & ($this->session->userdata('level')!='Pejabat Lelang'))
            {
                
                $this->load->library('form_validation');
                $eml =  ($this->input->post('kln_eml') !=  $data['klien']['kln_eml']) ? '|is_unique[tb_direktur.kln_eml]' : '';
                $jab =  ($this->input->post('kln_jab') !=  $data['klien']['kln_jab']) ? '|callback_cek_jab' : '';
                $this->form_validation->set_rules('kln_nm','Nama Lengkap','required|max_length[45]');
                $this->form_validation->set_rules('kln_tlp','Nomor Telepon','required|trim|min_length[10]|max_length[18]');
                $this->form_validation->set_rules('kln_alm','Alamat','required|max_length[255]');
                $this->form_validation->set_rules('kln_snd','Kata sandi','required|max_length[30]');
                $this->form_validation->set_rules('kln_eml','Email klien','required|valid_email|max_length[30]'.$eml);
                $this->rules();
                if($this->form_validation->run())     
                {   
                    $tgl = strtotime($this->input->post('kln_tll'));
                    $tgl = date('Y-m-d',$tgl);
                    $params = array(
                        'kln_nm' => $this->input->post('kln_nm'),
                        'kln_tlp' => trim($this->input->post('kln_tlp')),
                        'kln_alm' => $this->input->post('kln_alm'),
                        'kln_eml' => $this->input->post('kln_eml'),
                        'kln_snd' => $this->input->post('kln_snd'),
                );
                    $update = $this->M_klien->update_klien($this->session->userdata('id_login'),$params);  
                    /*if($update){
                         $login = array(
                        'id_login' => $data['klien']['kln_id'],
                        'nip' => $this->input->post('kln_nip'),
                        'nama' => $this->input->post('kln_nm'),
                        'email' => $this->input->post('kln_eml'),
                        'level' => $this->input->post('kln_jab'),
                        'sts' => 1,
                        'status' => "login"
                        );
                        $this->session->set_userdata($login);
                    }  */
                    redirect('klien/index');
                }
                 else
                {
                    $data['_view'] = 'v_klien/profile';
                    $data['_landing'] = false;
                    $data['judul'] = "Profil klien";
                    $load = $this->loader->load($data);
                    $this->load->view('layouts/content',$load);
                }
            
            }
            else
                redirect('login');
        }else{
            show_404();
        }
    }

    private function kodeotomatis()
        {
            $res = $this->db->query('select max(right(kln_no,11)) as `urut` from tb_direktur')->row();
            $tgl = date('/m.Y');
           // echo $res->urut.'<br>';
            if (isset($res->urut)) {
                //$urut = intval($res->urut);
                $urut = intval(substr($res->urut, 0,3));
                $bln = substr($res->urut, 4,2);
                $thn = substr($res->urut, 7,4);
/*                echo $urut.'<br>';
                echo $bln.'<br>';
                echo $thn.'<br>';
                echo substr($tgl, 1,2).'<br>';
                echo substr($tgl, 4,4).'<br>';*/
                if (substr($tgl, 1,2)==$bln) { ## bulan
                    if (substr($tgl, 4,4)==$thn) { ## tahun
                        if ($urut >= 999) {
                            $urut+=0;
                        }else{
                            $urut++;
                        }
                    }else{

                        $urut=1;
                    }
                }else{
                    $urut=1;
                }
            }else{
                $urut=1;
            }
            $str_length = strlen($urut);
            $dig = substr("000{$urut}", $str_length);
            return 'KLN-'.$dig.$tgl;
        }


    function info($kln_id)
    {   
        if ($this->session->has_userdata('status')) {
            // check if Data klien exists before trying to edit it
            $data['klien'] = $this->M_klien->get_klien($kln_id);
            
            if(isset($data['klien']['kln_id']))
            {
                $data['_view'] = 'v_klien/info';
                $data['_landing'] = false;
                $data['judul'] = "Data klien";
                $load = $this->loader->load($data);
                $this->load->view('layouts/content',$load);
            }
            else
                show_error('Data klien tidak ditemukan.');
        }else{
            show_404();
        }
    }
    /*
     * Deleting klien
     */
    public function nonactive()
    {
        $kln_id = $this->input->post('id');
       if ($this->session->has_userdata('status') && $this->session->userdata('level')=='Kepala Kantor') {
           $klien = $this->M_klien->get_klien($kln_id);

           // check if Data klien exists before trying to delete it
           if(isset($klien['kln_id']))
           {
                $params = array(
                    'kln_sts' => 0
                );
                $this->M_klien->update_klien($kln_id,$params);
                $pesan='
                    <!DOCTYPE html>
                    <html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
                    <head>
                        <meta charset="utf-8"> <!-- utf-8 works for most cases -->
                        <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldnt be necessary -->
                        <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
                        <meta name="x-apple-disable-message-reformatting">  <!-- Disable auto-scale in iOS 10 Mail entirely -->
                        <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

                        <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">

                        <!-- CSS Reset : BEGIN -->
                        <style>

                            /* What it does: Remove spaces around the email design added by some email clients. */
                            /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
                            html,
                    body {
                        margin: 0 auto !important;
                        padding: 0 !important;
                        height: 100% !important;
                        width: 100% !important;
                        background: #f1f1f1;
                    }

                    /* What it does: Stops email clients resizing small text. */
                    * {
                        -ms-text-size-adjust: 100%;
                        -webkit-text-size-adjust: 100%;
                    }

                    /* What it does: Centers email on Android 4.4 */
                    div[style*="margin: 16px 0"] {
                        margin: 0 !important;
                    }

                    /* What it does: Stops Outlook from adding extra spacing to tables. */
                    table,
                    td {
                        mso-table-lspace: 0pt !important;
                        mso-table-rspace: 0pt !important;
                    }

                    /* What it does: Fixes webkit padding issue. */
                    table {
                        border-spacing: 0 !important;
                        border-collapse: collapse !important;
                        table-layout: fixed !important;
                        margin: 0 auto !important;
                    }

                    /* What it does: Uses a better rendering method when resizing images in IE. */
                    img {
                        -ms-interpolation-mode:bicubic;
                    }

                    /* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */
                    a {
                        text-decoration: none;
                    }

                    /* What it does: A work-around for email clients meddling in triggered links. */
                    *[x-apple-data-detectors],  /* iOS */
                    .unstyle-auto-detected-links *,
                    .aBn {
                        border-bottom: 0 !important;
                        cursor: default !important;
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }

                    /* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */
                    .a6S {
                        display: none !important;
                        opacity: 0.01 !important;
                    }

                    /* What it does: Prevents Gmail from changing the text color in conversation threads. */
                    .im {
                        color: inherit !important;
                    }

                    /* If the above doesnt work, add a .g-img class to any image in question. */
                    img.g-img + div {
                        display: none !important;
                    }

                    /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */
                    /* Create one of these media queries for each additional viewport size youd like to fix */

                    /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */
                    @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
                        u ~ div .email-container {
                            min-width: 320px !important;
                        }
                    }
                    /* iPhone 6, 6S, 7, 8, and X */
                    @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
                        u ~ div .email-container {
                            min-width: 375px !important;
                        }
                    }
                    /* iPhone 6+, 7+, and 8+ */
                    @media only screen and (min-device-width: 414px) {
                        u ~ div .email-container {
                            min-width: 414px !important;
                        }
                    }


                        </style>

                        <!-- CSS Reset : END -->

                        <!-- Progressive Enhancements : BEGIN -->
                        <style>

                            .primary{
                        background: #6a5acd;
                    }
                    .bg_white{
                        background: #ffffff;
                    }
                    .bg_light{
                        background: #f7fafa;
                    }
                    .bg_black{
                        background: #000000;
                    }
                    .bg_dark{
                        background: rgba(0,0,0,.8);
                    }
                    .email-section{
                        padding:2.5em;
                    }

                    /*BUTTON*/
                    .btn{
                        padding: 10px 15px;
                        display: inline-block;
                    }
                    .btn.btn-primary{
                        border-radius: 5px;
                        background: #6a5acd;
                        color: #ffffff;
                    }
                    .btn.btn-white{
                        border-radius: 5px;
                        background: #ffffff;
                        color: #000000;
                    }
                    .btn.btn-white-outline{
                        border-radius: 5px;
                        background: transparent;
                        border: 1px solid #fff;
                        color: #fff;
                    }
                    .btn.btn-black-outline{
                        border-radius: 0px;
                        background: transparent;
                        border: 2px solid #000;
                        color: #000;
                        font-weight: 700;
                    }
                    .btn-custom{
                        color: rgba(0,0,0,.3);
                        text-decoration: underline;
                    }

                    h1,h2,h3,h4,h5,h6{
                        font-family: "Poppins", sans-serif;
                        color: #000000;
                        margin-top: 0;
                        font-weight: 400;
                    }

                    body{
                        font-family: "Poppins", sans-serif;
                        font-weight: 400;
                        font-size: 15px;
                        line-height: 1.8;
                        color: rgba(0,0,0,.4);
                    }

                    a{
                        color: #33cf;
                    }

                    table{
                    }
                    /*LOGO*/

                    .logo h1{
                        margin: 0;
                    }
                    .logo h1 a{
                        color: #339;
                        font-size: 24px;
                        font-weight: 700;
                        font-family: "Poppins", sans-serif;
                    }

                    /*HERO*/
                    .hero{
                        position: relative;
                        z-index: 0;
                    }

                    .hero .text{
                        color: rgba(0,0,0,.3);
                    }
                    .hero .text h2{
                        color: #000;
                        font-size: 34px;
                        margin-bottom: 0;
                        font-weight: 200;
                        line-height: 1.4;
                    }
                    .hero .text h3{
                        font-size: 24px;
                        font-weight: 300;
                    }
                    .hero .text h2 span{
                        font-weight: 600;
                        color: #000;
                    }

                    .text-author{
                        bordeR: 1px solid rgba(0,0,0,.05);
                        max-width: 50%;
                        margin: 0 auto;
                        padding: 2em;
                    }
                    .text-author img{
                        border-radius: 50%;
                        padding-bottom: 20px;
                    }
                    .text-author h3{
                        margin-bottom: 0;
                    }
                    ul.social{
                        padding: 0;
                    }
                    ul.social li{
                        display: inline-block;
                        margin-right: 10px;
                    }

                    /*FOOTER*/

                    .footer{
                        border-top: 1px solid rgba(0,0,0,.05);
                        color: rgba(0,0,0,.5);
                    }
                    .footer .heading{
                        color: #000;
                        font-size: 20px;
                    }
                    .footer ul{
                        margin: 0;
                        padding: 0;
                    }
                    .footer ul li{
                        list-style: none;
                        margin-bottom: 10px;
                    }
                    .footer ul li a{
                        color: rgba(0,0,0,1);
                    }


                    @media screen and (max-width: 500px) {


                    }


                        </style>


                    </head>

                    <body width="100%" style="margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;">
                        <center style="width: 100%; background-color: #f1f1f1;">
                        <div style="display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;">
                          &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
                        </div>
                        <div style="max-width: 600px; margin: 0 auto;" class="email-container">
                            <!-- BEGIN BODY -->
                          <table align="center" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="margin: auto;">
                            <tr>
                              <td valign="top" class="bg_white" style="padding: 1em 2.5em 0 2.5em;">
                                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                        <td class="logo" style="text-align: center;">
                                            <h1><a href="http://kpknl-bekasi.rf.gd">KPKNL Bekasi</a></h1>
                                          </td>
                                    </tr>
                                </table>
                              </td>
                              </tr><!-- end tr -->
                                    <tr>
                              <td valign="middle" class="hero bg_white" style="padding: 2em 0 4em 0;">
                                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                        <td style="padding: 0 2.5em; text-align: center; padding-bottom: 3em;">
                                            <div class="text">
                                                <h2>Mohon maaf, akun anda telah kami non aktifkan</h2>
                                                <p>Hal ini terjadi karena akun anda tidak memenuhi syarat dan ketentuan yang berlaku</p>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                          <td style="text-align: center;">
                                            <div class="text-author">
                                                <img src="http://bekasi.kpknl.rf.gd/assets/img/logo.png" alt="" style="width: 100px; max-width: 600px; height: auto; margin: auto; display: block;">
                                                <h3 class="name">'.$klien["kln_nm"].'</h3>
                                                <span class="position">'.$klien["kln_eml"].'</span>
                                                <p><a href="http://bekasi.kpknl.rf.gd/" class="btn btn-primary">Kunjungi situs</a></p>
                                            </div>
                                          </td>
                                        </tr>
                                </table>
                              </td>
                              </tr><!-- end tr -->
                          <!-- 1 Column Text + Button : END -->
                          </table>


                        </div>
                      </center>
                    </body>
                    </html>
                ';
                $kirim = array(
                    'pengirim'=>'KPKNL BEKASI',
                    'penerima'=>$klien['kln_eml'],
                    'pesan'=>$pesan,
                    'judul'=>'Status Akun Klien KPKNL Bekasi',
                );
                $this->kirim_email($kirim);
                redirect('klien/index');
           }else{
               show_error('Data klien yang dinonaktifkan tidak ditemukan.');
           }
       }else{
            show_404();
       }
    }

    

  public function active()
    {
       $kln_id = $this->input->post('id');
       if ($this->session->has_userdata('status') && $this->session->userdata('level')=='Kepala Kantor') {
           $klien = $this->M_klien->get_klien($kln_id);

           if(isset($klien['kln_id']))
           {
                $params = array(
                    'kln_sts' => 1
                );
                $this->M_klien->update_klien($kln_id,$params);
                $pesan='
                    <!DOCTYPE html>
                    <html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
                    <head>
                        <meta charset="utf-8"> <!-- utf-8 works for most cases -->
                        <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldnt be necessary -->
                        <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
                        <meta name="x-apple-disable-message-reformatting">  <!-- Disable auto-scale in iOS 10 Mail entirely -->
                        <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

                        <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">

                        <!-- CSS Reset : BEGIN -->
                        <style>

                            /* What it does: Remove spaces around the email design added by some email clients. */
                            /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
                            html,
                    body {
                        margin: 0 auto !important;
                        padding: 0 !important;
                        height: 100% !important;
                        width: 100% !important;
                        background: #f1f1f1;
                    }

                    /* What it does: Stops email clients resizing small text. */
                    * {
                        -ms-text-size-adjust: 100%;
                        -webkit-text-size-adjust: 100%;
                    }

                    /* What it does: Centers email on Android 4.4 */
                    div[style*="margin: 16px 0"] {
                        margin: 0 !important;
                    }

                    /* What it does: Stops Outlook from adding extra spacing to tables. */
                    table,
                    td {
                        mso-table-lspace: 0pt !important;
                        mso-table-rspace: 0pt !important;
                    }

                    /* What it does: Fixes webkit padding issue. */
                    table {
                        border-spacing: 0 !important;
                        border-collapse: collapse !important;
                        table-layout: fixed !important;
                        margin: 0 auto !important;
                    }

                    /* What it does: Uses a better rendering method when resizing images in IE. */
                    img {
                        -ms-interpolation-mode:bicubic;
                    }

                    /* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */
                    a {
                        text-decoration: none;
                    }

                    /* What it does: A work-around for email clients meddling in triggered links. */
                    *[x-apple-data-detectors],  /* iOS */
                    .unstyle-auto-detected-links *,
                    .aBn {
                        border-bottom: 0 !important;
                        cursor: default !important;
                        color: inherit !important;
                        text-decoration: none !important;
                        font-size: inherit !important;
                        font-family: inherit !important;
                        font-weight: inherit !important;
                        line-height: inherit !important;
                    }

                    /* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */
                    .a6S {
                        display: none !important;
                        opacity: 0.01 !important;
                    }

                    /* What it does: Prevents Gmail from changing the text color in conversation threads. */
                    .im {
                        color: inherit !important;
                    }

                    /* If the above doesnt work, add a .g-img class to any image in question. */
                    img.g-img + div {
                        display: none !important;
                    }

                    /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */
                    /* Create one of these media queries for each additional viewport size youd like to fix */

                    /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */
                    @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
                        u ~ div .email-container {
                            min-width: 320px !important;
                        }
                    }
                    /* iPhone 6, 6S, 7, 8, and X */
                    @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
                        u ~ div .email-container {
                            min-width: 375px !important;
                        }
                    }
                    /* iPhone 6+, 7+, and 8+ */
                    @media only screen and (min-device-width: 414px) {
                        u ~ div .email-container {
                            min-width: 414px !important;
                        }
                    }


                        </style>

                        <!-- CSS Reset : END -->

                        <!-- Progressive Enhancements : BEGIN -->
                        <style>

                            .primary{
                        background: #6a5acd;
                    }
                    .bg_white{
                        background: #ffffff;
                    }
                    .bg_light{
                        background: #f7fafa;
                    }
                    .bg_black{
                        background: #000000;
                    }
                    .bg_dark{
                        background: rgba(0,0,0,.8);
                    }
                    .email-section{
                        padding:2.5em;
                    }

                    /*BUTTON*/
                    .btn{
                        padding: 10px 15px;
                        display: inline-block;
                    }
                    .btn.btn-primary{
                        border-radius: 5px;
                        background: #6a5acd;
                        color: #ffffff;
                    }
                    .btn.btn-white{
                        border-radius: 5px;
                        background: #ffffff;
                        color: #000000;
                    }
                    .btn.btn-white-outline{
                        border-radius: 5px;
                        background: transparent;
                        border: 1px solid #fff;
                        color: #fff;
                    }
                    .btn.btn-black-outline{
                        border-radius: 0px;
                        background: transparent;
                        border: 2px solid #000;
                        color: #000;
                        font-weight: 700;
                    }
                    .btn-custom{
                        color: rgba(0,0,0,.3);
                        text-decoration: underline;
                    }

                    h1,h2,h3,h4,h5,h6{
                        font-family: "Poppins", sans-serif;
                        color: #000000;
                        margin-top: 0;
                        font-weight: 400;
                    }

                    body{
                        font-family: "Poppins", sans-serif;
                        font-weight: 400;
                        font-size: 15px;
                        line-height: 1.8;
                        color: rgba(0,0,0,.4);
                    }

                    a{
                        color: #33cf;
                    }

                    table{
                    }
                    /*LOGO*/

                    .logo h1{
                        margin: 0;
                    }
                    .logo h1 a{
                        color: #339;
                        font-size: 24px;
                        font-weight: 700;
                        font-family: "Poppins", sans-serif;
                    }

                    /*HERO*/
                    .hero{
                        position: relative;
                        z-index: 0;
                    }

                    .hero .text{
                        color: rgba(0,0,0,.3);
                    }
                    .hero .text h2{
                        color: #000;
                        font-size: 34px;
                        margin-bottom: 0;
                        font-weight: 200;
                        line-height: 1.4;
                    }
                    .hero .text h3{
                        font-size: 24px;
                        font-weight: 300;
                    }
                    .hero .text h2 span{
                        font-weight: 600;
                        color: #000;
                    }

                    .text-author{
                        bordeR: 1px solid rgba(0,0,0,.05);
                        max-width: 50%;
                        margin: 0 auto;
                        padding: 2em;
                    }
                    .text-author img{
                        border-radius: 50%;
                        padding-bottom: 20px;
                    }
                    .text-author h3{
                        margin-bottom: 0;
                    }
                    ul.social{
                        padding: 0;
                    }
                    ul.social li{
                        display: inline-block;
                        margin-right: 10px;
                    }

                    /*FOOTER*/

                    .footer{
                        border-top: 1px solid rgba(0,0,0,.05);
                        color: rgba(0,0,0,.5);
                    }
                    .footer .heading{
                        color: #000;
                        font-size: 20px;
                    }
                    .footer ul{
                        margin: 0;
                        padding: 0;
                    }
                    .footer ul li{
                        list-style: none;
                        margin-bottom: 10px;
                    }
                    .footer ul li a{
                        color: rgba(0,0,0,1);
                    }


                    @media screen and (max-width: 500px) {


                    }


                        </style>


                    </head>

                    <body width="100%" style="margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;">
                        <center style="width: 100%; background-color: #f1f1f1;">
                        <div style="display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;">
                          &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
                        </div>
                        <div style="max-width: 600px; margin: 0 auto;" class="email-container">
                            <!-- BEGIN BODY -->
                          <table align="center" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="margin: auto;">
                            <tr>
                              <td valign="top" class="bg_white" style="padding: 1em 2.5em 0 2.5em;">
                                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                        <td class="logo" style="text-align: center;">
                                            <h1><a href="http://kpknl-bekasi.rf.gd">KPKNL Bekasi</a></h1>
                                          </td>
                                    </tr>
                                </table>
                              </td>
                              </tr><!-- end tr -->
                                    <tr>
                              <td valign="middle" class="hero bg_white" style="padding: 2em 0 4em 0;">
                                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                        <td style="padding: 0 2.5em; text-align: center; padding-bottom: 3em;">
                                            <div class="text">
                                                <h2>Selamat, Akun anda telah disetujui !</h2>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                          <td style="text-align: center;">
                                            <div class="text-author">
                                                <img src="http://bekasi.kpknl.rf.gd/assets/img/logo.png" alt="" style="width: 100px; max-width: 600px; height: auto; margin: auto; display: block;">
                                                <h3 class="name">'.$klien["kln_nm"].'</h3>
                                                <span class="position">'.$klien["kln_eml"].'</span>
                                                <p><a href="http://bekasi.pknl.rf.gd/" class="btn btn-primary">Buat Permohonan</a></p>
                                            </div>
                                          </td>
                                        </tr>
                                </table>
                              </td>
                              </tr><!-- end tr -->
                          <!-- 1 Column Text + Button : END -->
                          </table>


                        </div>
                      </center>
                    </body>
                    </html>
                ';
                $kirim = array(
                    'pengirim'=>'KPKNL BEKASI',
                    'penerima'=>$klien['kln_eml'],
                    'pesan'=>$pesan,
                    'judul'=>'Status Akun Klien KPKNL Bekasi',
                );
                $this->kirim_email($kirim);
                redirect('klien/index');
           }
           else{
               show_error('Data klien yang diaktifkan tidak ditemukan.');
           }
       }else{
            show_404();
       }
    }

    public function login()
    {
        if ($this->session->has_userdata('status')) {
            if($this->session->userdata('sts')==0){
                echo '<script>alert("Tidak dapat mengkases dengan status non aktif");</script>';    
                //sleep(3);
                $this->session->sess_destroy();     
                //redirect('login');
            }else{
                redirect('dash');
            }
        }else{
            $this->load->library('form_validation');
            $this->form_validation->set_rules('u_email','Email atau NIP','required');
            $this->form_validation->set_rules('u_password','Password','required');
            if ($this->form_validation->run()) {
                $email = $this->input->post('u_email');
                $password = $this->input->post('u_password');
                $data['user'] = $this->M_klien->get_login($email,$password);
                if (isset($data['user']['kln_id'])) {
                    $data['klien'] = $this->M_klien->get_klien_by_nip($data['user']['kln_nip']);
                    $login = array(
                        'id_login' => $data['user']['kln_id'],
                        'nip' => $data['user']['kln_nip'],
                        'nama' => $data['user']['kln_nm'],
                        'email' => $data['user']['kln_eml'],
                        'level' => $data['user']['kln_jab'],
                        'sts' => $data['klien']['kln_sts'],
                        'status' => "login"
                        );
                    $this->session->set_userdata($login);
                    $this->login();
                    }else{
                        redirect('login');
                    }
                }
           
        }
       
    }

    function logout(){
        $this->session->sess_destroy();
        redirect('login');
    }

    function lupa_sandi()
    {
        if ($this->session->has_userdata('status')) {
            redirect('dash');
        }else{
            $this->load->library('form_validation');
            $this->form_validation->set_rules('u_email','Email','required');
            if ($this->form_validation->run()) {
                $kln_eml = $this->input->post('u_email');
                $data['klien'] = $this->M_klien->is_klien_with_email($kln_eml);
                if (isset($data['klien']['kln_snd'])) {
                 $pesan =  'ID : '.$data['klien']['kln_id'].'<br>'.'Email : '.$data['klien']['kln_eml'].'<br>'.'Kata sandi : '.$data['klien']['kln_snd'];
                    $kirim = array(
                        'pengirim'=>'KPKNL BEKASI',
                        'penerima'=>$data['klien']['kln_eml'],
                        'pesan'=>$pesan,
                        'judul'=>'Lupa kata sandi klien',
                    );
                    $this->kirim_email($kirim);
            echo '<script>alert("Ditemukan ! periksa kontak masuk pada alamat email '.$data['klien']['kln_eml'].' untuk melihat data.")</script>';
                    echo 'Ditemukan ! periksa kontak masuk pada alamat email '.$data['klien']['kln_eml'].' untuk melihat data.';
                }else{
                     echo '<script>alert("Email tidak valid.")</script>';
                redirect('forgot');
                }
             }else{
                 $data['_view'] = 'v_home/v_lupa';
                 $data['_landing'] = true;
                 $this->load->view('layouts/main',$data);
             }   
        }
    }

    private function kirim_email($konten='')
    {
        $config = $this->loader->config_email();
        $this->load->library('email', $config);
        $this->email->from($config['smtp_user'],   $konten['pengirim']);
        // Email penerima
        $this->email->to($konten['penerima']); // Ganti dengan email tujuan

        // Lampiran email, isi dengan url/path file
        if (isset($konten['lampiran'])) {
            $this->email->attach($konten['lampiran']);
        }

        // Subject email
        $this->email->subject($konten['judul']);

        // Isi email
        $this->email->message($konten['pesan']);

        $status = $this->email->send();
        if ($status) {
            sleep(3);
            echo '<script>alert(Sukses! Mohon periksa kontak masuk pada alamat email '.$konten['penerima'].');</script>';
            //redirect('login');
        } else {
            sleep(3);
            echo '<script>alert(Email tidak dapat dikirim.)</script>';
        }
    }

    
}
