<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Surat_masuk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_suratmasuk');
        $this->load->model('M_pegawai');
        $this->load->model('M_direktur');
        $this->load->model('M_permohonan');
        $this->load->library('Loader');
        $this->sesi = $this->session->has_userdata('status');
        if (!$this->sesi) {
            redirect('login','refresh');
        }
    } 

    /*
     * Listing of surat_masuk
     */
    function index()
    {
        if ($this->session->has_userdata('status')) {
            $params['limit'] = RECORDS_PER_PAGE; 
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
            
            $config = $this->config->item('pagination');
            $config['base_url'] = site_url('surat_masuk/index?');
            $config['total_rows'] = $this->M_suratmasuk->get_all_suratmasuk_count();
            $this->pagination->initialize($config);

            $data['surat_masuk'] = $this->M_suratmasuk->get_all_suratmasuk($params);
            $data['surat_masuk'] = array_map(function($val){
                $val['psl_srt'] = strip_tags($val['psl_srt']);
                return $val;
            },$data['surat_masuk']);
            // echo json_encode($data['surat_masuk']);
            // die();
            $data['_view'] = 'v_suratmasuk/index';
            $data['_landing'] = false;
            $data['judul'] = "Surat masuk";
            $load = $this->loader->load($data);
            $this->load->view('layouts/content',$load);
        }else{
            redirect('login');
        }
    }

    function rules(){
        $this->form_validation->set_message('max_length', '{field} tidk dapat lebih dari {param} karakter.');
        $this->form_validation->set_message('required', 'Memerlukan {field}.');
        $this->form_validation->set_message('is_unique', '{field} telah digunakan.');
    }

    private function kodeotomatis()
        {

            ///  S-999/WKN.08/9999
            $res = $this->db->query('select max(right(srtms_no,4)) as `urut_tahun`,max(substring(srtms_no,3,3)) as `urut` from tb_srtms')->row();
            $tgl = date('/Y');
            //echo $res->urut.'<br>';
            if (isset($res->urut)) {
                //$urut = intval($res->urut);
                $urut = intval($res->urut);
/*                echo $urut.'<br>';
                echo $bln.'<br>';
                echo $thn.'<br>';
                echo substr($tgl, 1,2).'<br>';
                echo substr($tgl, 4,4).'<br>';*/
                if (substr($tgl, 1,4)==$res->urut_tahun) { ## tahun
                    if ($urut >= 999) {
                            $urut+=0;
                    }else{
                            $urut++;
                    }
                }else{
                    $urut=1;
                }
            }else{
                $urut=1;
            }
            $str_length = strlen($urut);
            $dig = substr("000{$urut}", $str_length);
            return 'S-'.$dig.'/WKN.08'.$tgl;
    }

    function cetak($value){
        if($this->session->has_userdata('status') && $this->session->userdata('level')!='Kepala Kantor'){
            //if ($this->session->userdata('level')=='Admin') {
                $data['surat_masuk']= $this->M_suratmasuk->get_suratmasuk_by_join($value);
                //$data['surat_masuk']['pgw_nip']= $this->M_pegawai->get_pegawai_by_nip($data['surat_masuk']['pgw_nip']);
                if (isset($data['surat_masuk']['srtms_id'])) {
                    $data['surat_masuk']['kepala_kantor'] = $this->M_pegawai->search_pegawai('Kepala Kantor');
                    $data['nama_file']  = $data['surat_masuk']['psl_prh'].' - '.$this->loader->konversi_tanggal($data['surat_masuk']['srtms_tgl']);
                    $data['pdf'] = $this->load->library('PDFGenerator');
                    $html = $this->load->view('template/header_sm',$data, TRUE);
                    $this->pdfgenerator->generate($html,$data['nama_file']);
                }else{
                    redirect('surat_masuk');
                }
        /*  }else{
                redirect('login');
            }*/
        }else{
            redirect('login');
        }
    }

    public function cek_nip($nip){
       $nip = explode(' - ', $nip)[0];
       $cek = $this->M_pegawai->get_pegawai_by_nip($nip);

       if(!isset($cek))
       {
          $this->form_validation->set_message('cek_nip', 'Data tidak sesuai');
          return FALSE;
       } 
       return TRUE;
    }

    public function cek_no($no){
        $cek = intval(substr($no, 2,3));

        if($cek==999)
        {
           $this->form_validation->set_message('cek_no', 'Data telah mencapat batas pada bulan ini');
           return FALSE;
        } 
        return TRUE;
    }

    public function cek_psl($no){
       $cek = $this->M_permohonan->get_permohonan_by_no($no);
       if(!isset($cek[0]['psl_no']))
       {
          $this->form_validation->set_message('cek_psl', 'Nomor permohonan tidak sesuai');
          return FALSE;
       } 
       return TRUE;
    }

    /*
     * Adding a new surat_tuga
     */
    function add()
    {   
        if ($this->session->has_userdata('status') & ($this->session->userdata('level')=='Admin' || $this->session->userdata('level')=='Kepala Kantor')) {
            $this->load->library('form_validation');

            //$this->form_validation->set_rules('srtms_no','Nomor Surat','required|callback_cek_no');
            $this->form_validation->set_rules('srtms_sft','Sifat Surat','required');
            $this->form_validation->set_rules('psl_no','Nomor Permohonan','required|callback_cek_psl');
            $this->rules();
            if($this->form_validation->run())     
            {   
                //$tgl = strtotime($this->input->post('srtms_tgl'));
                $tgl = date('Y-m-d');
              //  $sts = ($this->session->userdata('level')=='Kepala Kantor' ? 1 : 0);
                /// 0 = belum ada surat tugas
                /// 1 = ada di surat tugas
                $params = array(
                    'srtms_no' => $this->kodeotomatis(),
                    'srtms_tgl' => $tgl,
                    'srtms_sft' => $this->input->post('srtms_sft'),
                    'psl_no' => $this->input->post('psl_no'),
                    'pgw_nip' => $this->session->userdata('nip'),
                    'srtms_sts' => '0'
                );
                
                $surat_masuk_id = $this->M_suratmasuk->add_suratmasuk($params);
                redirect('surat_masuk/index');
            }else{
                    $data['_view'] = 'v_suratmasuk/add';
                    $data['_landing'] = false;
                    $data['kode']=$this->kodeotomatis();
                    $data['judul'] = "Surat masuk";
                    $load = $this->loader->load($data);
                    $this->load->view('layouts/content',$load);
            }
        }else{
            redirect('surat_masuk');
        }
    }  

    function get_autocomplete(){
        if (isset($_GET['term'])) {
            $result = $this->M_suratmasuk->search_suratmasuk($_GET['term']);
            if (count($result) > 0) {
                foreach ($result as $row)
                   /* $arr_result[] = $row->srtms_no;
                    echo json_encode($arr_result);*/
                    $arr_result[] = array(
                            'label'         => $row->srtms_no,
                            'description'   => $row->srtms_tgl,
                    );
            }
            echo json_encode($arr_result);
            
        }
    }

    /*
     * Editing a surat_tuga
     */
    function edit($srtms_id)
    {   
    if ($this->session->has_userdata('status')& ($this->session->userdata('level')=='Admin' || $this->session->userdata('level')=='Kepala Kantor')) {
        // check if Data  surat_tuga exists before trying to edit it
        $data['srtms'] = $this->M_suratmasuk->get_suratmasuk($srtms_id);
        $pgw = $this->M_pegawai->get_pegawai_by_nip($data['srtms']['pgw_nip']);
        $data['srtms']['pgw_nip'] = $pgw['pgw_nip'].' - '.$pgw['pgw_nm'].' ('.$pgw['pgw_jab'].')';
        
        if(isset($data['srtms']['srtms_id']))
        {
            
            $this->load->library('form_validation');

            //$nomor =  ($this->input->post('srtms_no') !=  $data['srtms']['srtms_no']) ? '|is_unique[tb_srtms.srtms_no]' : '';
            
			//$this->form_validation->set_rules('srtms_no','Nomor Surat','required|callback_cek_no');
            $this->form_validation->set_rules('srtms_sft','Sifat Surat','required');
            $this->form_validation->set_rules('psl_no','Nomor Permohonan','required|callback_cek_psl');
            $this->rules();
			if($this->form_validation->run())     
            {   
                $tgl = strtotime($this->input->post('srtms_tgl'));
                $tgl = date('Y-m-d',$tgl);
                $params = array(
                    'srtms_sft' => $this->input->post('srtms_sft'),
                    'pgw_nip' => $this->session->userdata('nip'),
                    'psl_no' => $this->input->post('psl_no')
                );

                $this->M_suratmasuk->update_suratmasuk($srtms_id,$params);            
                redirect('surat_masuk/index');
            }
            else
            {
                $data['_view'] = 'v_suratmasuk/edit';
                $data['_landing'] = false;
                $data['judul'] = "Surat masuk";
                $load = $this->loader->load($data);
                $this->load->view('layouts/content',$load);
            }
        }
        else
            show_error('Data tidak ditemukan');
        }else{
            redirect('surat_masuk');
        }
    } 

    /*
     * Deleting surat_tuga
     */
    function remove()
    {
        $srtms_id = $this->input->post('id');
        if ($this->session->has_userdata('status') & ($this->session->userdata('level')=='Admin' || $this->session->userdata('level')=='Kepala Kantor')) {
        
        $surat_masuk = $this->M_suratmasuk->get_suratmasuk($srtms_id);

        // check if Data  surat_tuga exists before trying to delete it
        if(isset($surat_masuk['srtms_id']))
        {
            $this->M_suratmasuk->delete_suratmasuk($srtms_id);
            redirect('surat_masuk/index');
        }
        else
            show_error('Data tidak ditemukan');
        }else{
            redirect('surat_masuk');
        }
    }
    
}
