<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{

    private $sesi;
    function __construct()
    {
        parent::__construct();
        $this->load->library('Loader');
        $this->load->model('M_pegawai');
        $this->load->model('M_suratmasuk');
        $this->load->model('M_surattugas');
        $this->load->model('M_permohonan');
        $sesi = $this->session->has_userdata('status');
        if (!$sesi) {
            $data['_view'] = 'v_home/index';
            $data['_landing'] = true;
            $this->load->view('layouts/content',$data);
        }
    }

    function index()
    {

        if (($this->session->userdata['status']=='login')) {
            $data['_view']      = 'dashboard';   
            $data['_landing']   = false;
            $data['judul']      = "Halaman utama";
            $data['jml_pgw']    = $this->M_pegawai->get_all_pegawai_count();
            $data['jml_sm']     = $this->M_suratmasuk->get_all_suratmasuk_count();
            $data['jml_st']     = $this->M_surattugas->get_all_surattugas_count();
            $data['jml_psl']    = $this->M_permohonan->get_all_permohonan_count();
            $data['surat']      = $this->M_suratmasuk->get_status_surat();
            $data['permohonan'] = $this->db->query("select p.psl_no,IFNULL(k.direktur_nm,'-') as direktur_nm,p.psl_tgl,p.psl_prh from tb_psl p left join tb_direktur k on p.direktur_no = k.direktur_no limit 5")->result_array();
            $load = $this->loader->load($data);
            $this->load->view('layouts/content',$load);
        } else {
            redirect('login');
        }
    }
}
