<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_pegawai');
    } 

    /*
     * Listing of user
     */
    function index()
    {

        if (($this->session->userdata['status']=='login')) {
            redirect('dash');
        } else {
            redirect('login');
        }
    }

    /*
     * Adding a new user
     */
/*    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('usr_lvl','Usr Lvl','required|max_length[16]');
		$this->form_validation->set_rules('pgw_nip','Pgw Nip','required|max_length[25]');
		$this->form_validation->set_rules('usr_eml','Usr Eml','required');
		$this->form_validation->set_rules('usr_snd','Usr Snd','required|max_length[30]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'usr_lvl' => $this->input->post('usr_lvl'),
				'pgw_nip' => $this->input->post('pgw_nip'),
				'usr_eml' => $this->input->post('usr_eml'),
				'usr_snd' => $this->input->post('usr_snd'),
            );
            
            $user_id = $this->M_user->add_user($params);
            redirect('user/index');
        }
        else
        {            
            $data['_view'] = 'v_home/register';
            $this->load->view('layouts/main',$data);
        }
    }  */

    /*
     * Editing a user
     */
   /* function edit($usr_id)
    {   
        $data['user'] = $this->M_user->get_user($usr_id);
        
        if(isset($data['user']['usr_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('usr_lvl','Usr Lvl','required|max_length[16]');
			$this->form_validation->set_rules('pgw_nip','Pgw Nip','required|max_length[25]');
			$this->form_validation->set_rules('usr_eml','Usr Eml','required');
			$this->form_validation->set_rules('usr_snd','Usr Snd','required|max_length[30]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'usr_lvl' => $this->input->post('usr_lvl'),
					'pgw_nip' => $this->input->post('pgw_nip'),
					'usr_eml' => $this->input->post('usr_eml'),
					'usr_snd' => $this->input->post('usr_snd'),
                );

                $this->M_user->update_user($usr_id,$params);            
                redirect('user/index');
            }
            else
            {
                $data['_view'] = 'user/edit';
                $data['_landing'] = false;
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } */

    public function login()
    {
        if ($this->session->has_userdata('status')) {
            redirect('dash');
        }else{
            $this->load->library('form_validation');
            $this->form_validation->set_rules('u_email','Email','required');
            $this->form_validation->set_rules('u_password','Password','required');
            if ($this->form_validation->run()) {
                $email = $this->input->post('u_email');
                $password = $this->input->post('u_password');
                $data['user'] = $this->M_pegawai->get_login($email,$password);
                if (isset($data['user']['usr_id'])) {
                    $data['pegawai'] = $this->M_pegawai->get_pegawai_by_nip($data['user']['pgw_nip']);
                    $login = array(
                        'nip' => $data['user']['pgw_nip'],
                        'nama' => $data['pegawai']['pgw_nm'],
                        'email' => $data['user']['usr_eml'],
                        'level' => $data['user']['usr_lvl'],
                        'status' => "login"
                        );
                    $this->session->set_userdata($login);
                    redirect('dash');
                }
            }
        }
       
    }

    function logout(){
        $this->session->sess_destroy();
        redirect(base_url('login'));
    }
    
}
