<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_direktur extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

    function get_login($username,$usr_pass)
    {
        $sql = "SELECT * FROM tb_direktur WHERE direktur_eml = ?  AND direktur_snd = ?";
        return $this->db->query($sql, array($username, $usr_pass))->result_array();
    }
    
    /*
     * Get tb_direktur by direktur_id
     */
    function get_direktur($direktur_id)
    {
        return $this->db->get_where('tb_direktur',array('direktur_id'=>$direktur_id))->row_array();
    }

    function get_direktur_by_no($direktur_no)
    {
        return $this->db->get_where('tb_direktur',array('direktur_no'=>$direktur_no))->row_array();
    }

    function get_direktur_on_suratmasuk($direktur_id)
    {
        $this->db->join('tb_direktur', 'tb_direktur.direktur_id = tb_srtms.direktur_id', 'left');
        return $this->db->get_where('tb_srtms',array('tb_srtms.direktur_id'=>$direktur_id))->row_array();
    }

    /*
     * Get all tb_direktur count
     */
    function get_all_direktur_count()
    {
        $this->db->from('tb_direktur');
        return $this->db->count_all_results();
    }

    function is_direktur_with_email($email){
           return $this->db->query("select * from tb_direktur where direktur_eml = '$email' ")->row_array();
    }


    function search_direktur($cari){
        $this->db->like('direktur_no', $cari , 'both');
        $this->db->or_like('direktur_nm', $cari , 'both');
        $this->db->order_by('direktur_nm', 'ASC');
        $this->db->limit(3);
        return $this->db->get('tb_direktur')->result();
    }
        
    /*
     * Get all tb_direktur
     */
    function get_all_direktur($params = array())
    {
        $this->db->order_by('direktur_nm', 'ASC');
        //$kecuali = array('Kepala Sub Bagian Umum','Admin' );
        //$this->db->where_not_in('direktur_jab', $kecuali);
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_direktur')->result_array();
    }
       
        function get_all($params = array())
    {
        $this->db->order_by('direktur_nm', 'ASC');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_direktur')->result_array();
    }

    function get_all_direktur_result()
    {
        $this->db->order_by('direktur_nm', 'ASC');
        //$kecuali = array('Kepala Sub Bagian Umum','Admin' );
        //$this->db->where_not_in('direktur_jab', $kecuali);
        return $this->db->get('tb_direktur')->result();
    }
        
    /*
     * function to add new tb_direktur
     */
    function add_direktur($params)
    {
        $this->db->insert('tb_direktur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_direktur
     */
    function update_direktur($direktur_id,$params)
    {
        $this->db->where('direktur_id',$direktur_id);
        return $this->db->update('tb_direktur',$params);
    }
    
    /*
     * function to delete tb_direktur
     */
    function delete_direktur($direktur_id)
    {   $this->db->where('direktur_id', $direktur_id);
        return $this->db->delete('tb_direktur');
    }
}
