<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_notadinas extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get nota_dina by nds_no
     */
    function get_nota_dinas($nds_id)
    {
        return $this->db->get_where('tb_nds',array('nds_id'=>$nds_id))->row_array();
    }
    
    /*
     * Get all nota_dinas count
     */
    function get_all_nota_dinas_count()
    {
        $this->db->from('tb_nds');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all nota_dinas
     */
    function get_all_nota_dinas($params = array())
    {
        $this->db->order_by('nds_tgl', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_nds')->result_array();
    }
        
    /*
     * function to add new nota_dina
     */
    function add_nota_dinas($params)
    {
        $this->db->insert('tb_nds',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update nota_dina
     */
    function update_nota_dinas($nds_id,$params)
    {
        $this->db->where('nds_id',$nds_id);
        return $this->db->update('tb_nds',$params);
    }
    
    /*
     * function to delete nota_dina
     */
    function delete_nota_dinas($nds_id)
    {
        return $this->db->delete('tb_nds',array('nds_id'=>$nds_id));
    }
}
