<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_pengikuttgs extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pengikut_tgs by ptgs_id
     */
    function get_pengikut_tgs($ptgs_id)
    {
        return $this->db->get_where('tb_pgtgs',array('ptgs_id'=>$ptgs_id))->row_array();
    }

    function get_pengikut_tgs_by_no($srtgs_no)
    {   $q = $this->db->query('select pgw_nip from tb_pgtgs where srtgs_no = "'.$srtgs_no.'"');
        //echo var_dump($q->result());
        return $q->result();
    }
        function get_pengikut_tgs_by_no_join($srtgs_no)
    {   
        $this->db->join('tb_pgw', 'tb_pgtgs.pgw_nip = tb_pgw.pgw_nip', 'left');
    //var_dump($this->db->get_where('tb_pgtgs',array('srtgs_no'=>$srtgs_no))->row_array());
        return $this->db->get_where('tb_pgtgs',array('srtgs_no'=>$srtgs_no))->result();
    }
       
/*       function count_pengikut_tgs_by_no($srtgs_no)
    {
        var_dump($this->db->get_where('tb_pgtgs',array('srtgs_no'=>$srtgs_no))->count_all_results());
        return $this->db->get_where('tb_pgtgs',array('srtgs_no'=>$srtgs_no))->count_all_results();
    }*/
    
    /*
     * Get all pengikut_tgs count
     */
    function get_all_pengikut_tgs_count()
    {
        $this->db->from('tb_pgtgs');
        return $this->db->count_all_results();
    }


        function count_by_no($srtgs_no)
    {
        $query = $this->db->query("select count(*) as cnt from tb_pgtgs where srtgs_no = '".$srtgs_no."'");
        //var_dump($query->row_array()['cnt']);
        //var_dump($query->result()->cnt);
        return $query->row_array();
    }
        
    /*
     * Get all pengikut_tgs
     */
    function get_all_pengikut_tgs($params = array())
    {
        $this->db->order_by('ptgs_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_pgtgs')->result_array();
    }
        
    /*
     * function to add new pengikut_tgs
     */
    function add_pengikut_tgs($params)
    {
        $this->db->insert('tb_pgtgs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pengikut_tgs
     */
    function update_pengikut_tgs($ptgs_id,$params)
    {
        $this->db->where('srtgs_no',$ptgs_id);
        return $this->db->update('tb_pgtgs',$params);
    }
    
    /*
     * function to delete pengikut_tgs
     */
    function delete_pengikut_tgs($ptgs_id)
    {
        return $this->db->delete('tb_pgtgs',array('srtgs_no'=>$ptgs_id));
    }
    function delete_pengikut_tgs_pgw($ptgs_id,$nip_pgw)
    {
        return $this->db->delete('tb_pgtgs',array('srtgs_no'=>$ptgs_id,'pgw_nip'=>$nip_pgw));
    }
}
