<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_suratmasuk extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function search_suratmasuk($no){
        $this->db->like('srtms_no', $no , 'both');
        //$this->db->order_by('srtms_prh', 'ASC');
        $this->db->limit(3);
        return $this->db->get('tb_srtms')->result();
    }
    
    /*
     * Get surat_masuk by srtms_id
     */
    function get_suratmasuk($sm_id)
    {
        $this->db->join('tb_psl', 'tb_srtms.psl_no = tb_psl.psl_no', 'left');
        $this->db->join('tb_direktur', 'tb_psl.direktur_no = tb_direktur.direktur_no', 'left');
        return $this->db->get_where('tb_srtms',array('srtms_id'=>$sm_id))->row_array();
    }

        function get_suratmasuk_by_no($sm_no)
    {
        $this->db->join('tb_psl', 'tb_srtms.psl_no = tb_psl.psl_no', 'left');
        return $this->db->get_where('tb_srtms',array('srtms_no'=>$sm_no))->row_array();
    }

    function get_suratmasuk_by_join($sm_id)
    {
        $this->db->join('tb_psl', 'tb_srtms.psl_no = tb_psl.psl_no', 'left');
        $this->db->join('tb_pgw', 'tb_srtms.pgw_nip = tb_pgw.pgw_nip', 'left');
        $this->db->join('tb_direktur', 'tb_psl.direktur_no = tb_direktur.direktur_no', 'left');
        return $this->db->get_where('tb_srtms',array('tb_srtms.srtms_id'=>$sm_id))->row_array();
    }
    
    /*
     * Get all surat_masuk count
     */
    function get_all_suratmasuk_count()
    {
        $this->db->from('tb_srtms');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all surat_masuk
     */
    function get_all_suratmasuk_bak($params = array())
    {
        $this->db->join('tb_pgw', 'tb_pgw.pgw_nip = tb_srtms.pgw_nip', 'left');
        $this->db->order_by('srtms_no', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_srtms')->result_array();
    }
        function get_all_suratmasuk($params = array())
    {
        $this->db->join('tb_psl', 'tb_srtms.psl_no = tb_psl.psl_no', 'left');
        $this->db->join('tb_direktur', 'tb_psl.direktur_no = tb_direktur.direktur_no', 'left');
        $this->db->join('tb_pgw', 'tb_srtms.pgw_nip = tb_pgw.pgw_nip', 'left');
        $this->db->order_by('tb_srtms.srtms_no', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_srtms')->result_array();
    }


    function get_status_surat()
    {
        $this->db->select("IFNULL(tb_psl.psl_no,'-') as `psl_no`,IFNULL(tb_srtms.srtms_no,'-') as `srtms_no`, IFNULL(tb_psl.psl_tgl,'-') as `psl_tgl`, IFNULL(tb_srtms.srtms_tgl,'-') as `srtms_tgl`, IFNULL(tb_psl.psl_prh,'-') as `psl_prh`, IFNULL(tb_srtgs.srtgs_sts,0) as `srtgs_sts`,IFNULL(tb_srtgs.srtgs_tgl,'-') as `srtgs_tgl`");
        $this->db->from("tb_srtms");
        $this->db->join('tb_psl', 'tb_srtms.psl_no = tb_psl.psl_no', 'left');
        $this->db->join('tb_srtgs', 'tb_srtgs.srtms_no = tb_srtms.srtms_no', 'left');
        $this->db->order_by('tb_psl.psl_tgl', 'desc');
        $this->db->limit(10);
        //$this->db->where('tb_srtms.srtms_tgl between date_sub(NOW(),interval 14 DAY) and NOW()');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new surat_masuk
     */
    function add_suratmasuk($params)
    {
        $this->db->insert('tb_srtms',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update surat_masuk
     */
    function update_suratmasuk($srtms_id,$params)
    {
        $this->db->where('srtms_id',$srtms_id);
        return $this->db->update('tb_srtms',$params);
    }
    
    /*
     * function to delete surat_masuk
     */
    function delete_suratmasuk($srtms_id)
    {
        return $this->db->delete('tb_srtms',array('srtms_id'=>$srtms_id));
    }
}
